### ISSUE TITLE
indirect buffers not saved by persp-save-state-to-file doesn't save

### ISSUE THREAD

**Issue by notuntoward** [Bad-ptr/persp-mode.el#93]
I like persp-mode but wish that it could have indirect files (the result of, for example `clone-indirect-buffer-other-window`).   <br /><br /> 

Say I have a file named   <br /><br /> 

_~/tmp/tmp.txt_ <br /><br /> 

and that I've cloned it, so that I have another buffer viewing the same file.  The emacs modeline will call this _~/tmp/tmp.txt<2>_.<br /> <br /> 

Then, if I save the window configuration with `persp-save-state-to-file`, kill emacs, and then try to restore the config with `persp-load-state-from-file`, then the buffer positions will be correctly restored; the file _~/tmp/tmp.txt_ will be reloaded; and it will be in its original buffer.  <br /> <br /> 

However, the buffer where the indirect buffer was will be blank, and it will be given the name _-tmp.txt<2>_<br /> <br /> 

It looks like persp-mode is trying to load a file named _-tmp.txt<2>_ instead of recreating the indirect view.

**Comment by Bad-ptr** [comment]
I updated the code in the previous post. But before running it, you must update the `persp-mode`.

**Comment by codygman** [comment]
@Bad-ptr Your code above seemed to work, but then I noticed the indirect buffer had the entire contents of the file it was derived from. Is there anyway to make sure the indirect buffer is only the part of the buffer you cloned?

Here's an example:

![persp-mode-org-indirect-buf-issue](https://user-images.githubusercontent.com/225847/46390530-e2adb480-c69d-11e8-95cb-bef1bf091605.gif)

**Comment by notuntoward** [comment]
With the latest persp-mode, I no longer get error messages but still can't save indirect buffers.  There is also now a problem with package-autoremove.

With the latest persp-mode, I can save emacs buffer state with M-x persp-save-state-to-file, kill/restart emacs, and then restore the state with M-x persp-load-state-from-file.  This correctly loads the files I was visiting before.  If there were no indirect buffers, there are no other messages.

However, if I save/load an emacs state containing an indrect buffer, I get a minibuffer full of code and the indirect buffer is not restored.   All the files are loaded in some buffer but only a blank scratch buffer is shown (screenshot below).

<img width="623" alt="buffer-full-of-code" src="https://user-images.githubusercontent.com/3851891/46933439-5794cd00-d054-11e8-9201-5c820d276e58.PNG">

I should say that I'm also using the custom save/load function contributed by @Bad-ptr on May 26.

The other problems is that M-x package auto-remove now thinks that persp-mode is unused and wants to delete it.  It looks like persp-mode isn't registering itself with the package manager, somehow.

This is on Windows emacs 26.1, and with the attached perp-mode invocation in my .emacs:

[persp-mode-in-dotemacs.txt](https://github.com/Bad-ptr/persp-mode.el/files/2477617/persp-mode-in-dotemacs.txt)
